import { test, expect, describe, vi } from "vitest";

// E2E Simulation for StudyQuest (Fasa 1 - Fasa 4)
// Mocking DB states to simulate the cross-function behavior

import { calculateSubtopicBreakdown } from "./masteryEngine.ts";

describe("StudyQuest E2E Journey Simulation (Fasa 1-4)", () => {

  const TOPIC_ID = "TOPIC_001";
  const SUBTOPIC_1 = "SUB_001";
  const SUBTOPIC_2 = "SUB_002";
  const STUDENT_ID = "STU_999";

  // Simulate Questions generated by Fasa 2 (10 questions, N x 5)
  const fasa2GeneratedQuestions = [
    // Subtopic 1 (5 questions)
    { id: "Q1", subtopic_id: SUBTOPIC_1, tp_level: 1 },
    { id: "Q2", subtopic_id: SUBTOPIC_1, tp_level: 2 },
    { id: "Q3", subtopic_id: SUBTOPIC_1, tp_level: 3 },
    { id: "Q4", subtopic_id: SUBTOPIC_1, tp_level: 4 },
    { id: "Q5", subtopic_id: SUBTOPIC_1, tp_level: 5 },
    // Subtopic 2 (5 questions)
    { id: "Q6", subtopic_id: SUBTOPIC_2, tp_level: 1 },
    { id: "Q7", subtopic_id: SUBTOPIC_2, tp_level: 2 },
    { id: "Q8", subtopic_id: SUBTOPIC_2, tp_level: 3 },
    { id: "Q9", subtopic_id: SUBTOPIC_2, tp_level: 4 },
    { id: "Q10", subtopic_id: SUBTOPIC_2, tp_level: 6 },
  ];

  test("Step 1: AI Question Generation (Fasa 2 Verification)", () => {
    // Assert 5 questions per subtopic
    const sub1Count = fasa2GeneratedQuestions.filter(q => q.subtopic_id === SUBTOPIC_1).length;
    const sub2Count = fasa2GeneratedQuestions.filter(q => q.subtopic_id === SUBTOPIC_2).length;
    
    expect(fasa2GeneratedQuestions.length).toBe(10);
    expect(sub1Count).toBe(5);
    expect(sub2Count).toBe(5);
    // Check TP existence
    expect(fasa2GeneratedQuestions.some(q => q.tp_level === 6)).toBe(true);
  });

  let gatewayState: any = {};
  let subtopicMasteryState: Record<string, any> = {};

  test("Step 2 & 3: Student Fails Mastery & Remediation Triggers (Fasa 1 & 3)", () => {
    // Simulate Student taking the test
    // Subtopic 1: 4/5 correct (80%) -> PASS
    // Subtopic 2: 2/5 correct (40%) -> FAIL
    
    const answers = [
      // SUB 1
      { question_id: "Q1", is_correct: true, subtopic_id: SUBTOPIC_1, tp_level: 1 },
      { question_id: "Q2", is_correct: true, subtopic_id: SUBTOPIC_1, tp_level: 2 },
      { question_id: "Q3", is_correct: true, subtopic_id: SUBTOPIC_1, tp_level: 3 },
      { question_id: "Q4", is_correct: true, subtopic_id: SUBTOPIC_1, tp_level: 4 },
      { question_id: "Q5", is_correct: false, subtopic_id: SUBTOPIC_1, tp_level: 5 },
      // SUB 2
      { question_id: "Q6", is_correct: true, subtopic_id: SUBTOPIC_2, tp_level: 1 },
      { question_id: "Q7", is_correct: true, subtopic_id: SUBTOPIC_2, tp_level: 2 },
      { question_id: "Q8", is_correct: false, subtopic_id: SUBTOPIC_2, tp_level: 3 },
      { question_id: "Q9", is_correct: false, subtopic_id: SUBTOPIC_2, tp_level: 4 },
      { question_id: "Q10", is_correct: false, subtopic_id: SUBTOPIC_2, tp_level: 6 },
    ];

    // Fasa 1 evaluateDiagnosticQuiz core logic
    const gatewayResult = calculateSubtopicBreakdown(answers);

    // Save state to our DB Mocks
    gatewayState = { is_unlocked: gatewayResult.isTopicUnlocked };
    gatewayResult.subtopics.forEach(sub => {
      subtopicMasteryState[sub.subtopic_id] = {
        status: sub.is_passed ? 'MASTERED' : 'REMEDIATION_REQUIRED',
        score: sub.score_percentage
      };
    });

    // Step 2 Asserts (Backend)
    expect(gatewayState.is_unlocked).toBe(false); // Gateway Locked
    expect(subtopicMasteryState[SUBTOPIC_1].status).toBe('MASTERED');
    expect(subtopicMasteryState[SUBTOPIC_2].status).toBe('REMEDIATION_REQUIRED');

    // Step 3 Asserts (Student UI Trigger check)
    // The UI relies on failed_subtopic_ids array
    expect(gatewayResult.failedSubtopicIds).toContain(SUBTOPIC_2);
    expect(gatewayResult.failedSubtopicIds).not.toContain(SUBTOPIC_1);
  });

  test("Step 4: Parent Dashboard Real-Time Reflection (Fasa 4)", () => {
    // Fetch state for Parent UI
    const parentViewData = Object.values(subtopicMasteryState);
    
    // Check if Parent Action Card should trigger Red Alert
    const needsRemediation = parentViewData.some(m => m.status === 'REMEDIATION_REQUIRED');
    
    expect(needsRemediation).toBe(true);
    // UI logic will pick up SUB_002 for the hint
    const weakSubtopic = Object.keys(subtopicMasteryState).find(k => subtopicMasteryState[k].status === 'REMEDIATION_REQUIRED');
    expect(weakSubtopic).toBe(SUBTOPIC_2);
  });

  test("Step 5: Scenario B - Student Retakes & Passes (Fasa 1 & 4 Update)", () => {
    // Simulate Student taking ONLY Subtopic 2 again (Remediation Retry)
    // 4/5 correct (80%) -> PASS
    const answersRetry = [
      { question_id: "Q6", is_correct: true, subtopic_id: SUBTOPIC_2, tp_level: 1 },
      { question_id: "Q7", is_correct: true, subtopic_id: SUBTOPIC_2, tp_level: 2 },
      { question_id: "Q8", is_correct: true, subtopic_id: SUBTOPIC_2, tp_level: 3 },
      { question_id: "Q9", is_correct: true, subtopic_id: SUBTOPIC_2, tp_level: 4 },
      { question_id: "Q10", is_correct: false, subtopic_id: SUBTOPIC_2, tp_level: 6 },
    ];

    // Combine previous passing states with new retry states
    // The engine expects all answers or processes just the current ones. We'll pass the full suite for gateway eval.
    const allAnswers = [
      // Pass from before
      { question_id: "Q1", is_correct: true, subtopic_id: SUBTOPIC_1, tp_level: 1 },
      { question_id: "Q2", is_correct: true, subtopic_id: SUBTOPIC_1, tp_level: 2 },
      { question_id: "Q3", is_correct: true, subtopic_id: SUBTOPIC_1, tp_level: 3 },
      { question_id: "Q4", is_correct: true, subtopic_id: SUBTOPIC_1, tp_level: 4 },
      { question_id: "Q5", is_correct: false, subtopic_id: SUBTOPIC_1, tp_level: 5 },
      // New Pass
      ...answersRetry
    ];

    const gatewayResult = calculateSubtopicBreakdown(allAnswers);

    gatewayState = { is_unlocked: gatewayResult.isTopicUnlocked };
    gatewayResult.subtopics.forEach(sub => {
      subtopicMasteryState[sub.subtopic_id] = {
        status: sub.is_passed ? 'MASTERED' : 'REMEDIATION_REQUIRED',
        score: sub.score_percentage
      };
    });

    // Asserts
    expect(gatewayState.is_unlocked).toBe(true); // GATEWAY IS NOW OPEN
    expect(subtopicMasteryState[SUBTOPIC_2].status).toBe('MASTERED');
    expect(subtopicMasteryState[SUBTOPIC_2].score).toBe(80);

    // Parent UI should no longer have Remediation triggers
    const parentAlerts = Object.values(subtopicMasteryState).some(m => m.status === 'REMEDIATION_REQUIRED');
    expect(parentAlerts).toBe(false); // Parent sees Green!
  });

});
