import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { getStudentHome } from '../services/studentJourneyService';
import XPHeader from '../components/student/XPHeader';
import MasteryProgress from '../components/student/MasteryProgress';
import MissionCard from '../components/student/MissionCard';

export default function StudentHome() {
  const navigate = useNavigate();
  const [homeData, setHomeData] = useState(null);

  useEffect(() => {
    async function loadData() {
      // In a real app, this comes from auth context
      const studentId = localStorage.getItem('currentStudentId') || 'stu_demo';
      const studentName = localStorage.getItem('currentStudentName') || 'Pengembara';
      
      // Fetch data generated by the backend Recommendation & Mastery engines via DB Repos
      const data = await getStudentHome(studentId, studentName, 'KSSR_SEMAKAN', 'Tahun 1', 'Matematik');
      setHomeData(data);
    }
    loadData();
  }, []);

  if (!homeData) return <div className="p-10 text-center text-gray-500 font-bold">Memuatkan data AI...</div>;

  const handleStartMission = (mission) => {
    // Pass mission state into the actual lesson rendering page (built in Phase 1)
    navigate('/lesson', { state: { mission } });
  };

  return (
    <div className="min-h-screen bg-[#F5F7FA] pb-20">
      
      {/* 1. Global HUD */}
      <XPHeader 
        studentName={homeData.studentName}
        xp={homeData.xp}
        streak={homeData.streak}
      />

      <main className="max-w-md mx-auto px-4 mt-6 space-y-6">
        
        {/* 2. Today's Recommended Mission */}
        <section>
          <div className="flex justify-between items-center mb-3 px-1">
            <h2 className="font-bold text-gray-800 text-lg">Misi Utama</h2>
          </div>
          <MissionCard 
            mission={homeData.todayMission} 
            onStartMission={handleStartMission} 
          />
        </section>

        {/* 3. High-level Mastery Visualization */}
        <section>
          <div className="flex justify-between items-center mb-3 px-1">
            <h2 className="font-bold text-gray-800 text-lg">Perkembangan</h2>
          </div>
          <MasteryProgress 
            subjectName={homeData.currentLevel}
            progressPercentage={homeData.progressPercentage}
          />
        </section>

        {/* 4. Adaptive Weak Area Hints */}
        {homeData.weakAreas && homeData.weakAreas.length > 0 && (
          <section>
            <div className="flex justify-between items-center mb-3 px-1">
              <h2 className="font-bold text-gray-800 text-lg">Topik untuk Kuatkan</h2>
            </div>
            <div className="bg-orange-50 border border-orange-100 rounded-2xl p-4 flex gap-3">
              <div className="text-2xl">💪</div>
              <div>
                <p className="text-orange-900 text-sm font-medium">Kami akan bantu anda menguasai:</p>
                <p className="text-orange-700 text-xs font-bold mt-1">
                  {homeData.weakAreas.slice(0, 2).join(', ')}
                </p>
              </div>
            </div>
          </section>
        )}

      </main>

    </div>
  );
}
